### ISSUE TITLE
Often stops working

### ISSUE THREAD

**Issue by thalesnabreu** [anishaaa1/Minimal-Clozes#2]
Often the plugin stops working and no longer shows. It's a shame 'cause I absolutely love this plugin. Is there anything I can do to force it to load? (I'm on iPad)

**Comment by anishaaa1** [comment]
@thalesnabreu Hi, sorry for the late response! I am looking into this issue (facing it myself), and will let you know when I have an update. Thank you :)

**Comment by anishaaa1** [comment]
I will be closing this issue for now, but please let me know in case it recurs. Thank you :)
